### ISSUE TITLE
Status and possible release on Hackage

### ISSUE THREAD

**Issue by guaraqe** [ttuegel/arpack#1]
Hello!

I found this repo while looking for arpack bindings. Currently the only released option is [HEigs](https://hackage.haskell.org/package/HEigs) which is very incomplete, and I put together complementary bindings [here](https://github.com/guaraqe/harpack), but yours are clearly better made than mine.

I would like to know if you plan to release this library on Hackage and if you feel it is ready to use.

Thank you very much!

**Comment by ttuegel** [comment]
I think it is ready to use. The bindings don't cover _all_ the features of ARPACK, but I think they cover the most-used features. I have used them for Real Work. I have uploaded a release to [Hackage](http://hackage.haskell.org/package/arpack).
